### PR TITLE
Support Various Prometheus Client Versions

### LINKED ISSUE #128: ImportError: cannot import name 'choose_encoder' from 'prometheus_client.exposition'
Newest prometheus_client 0.14 breaks compatibility (choose_encoder was removed)

### PR DESCRIPTION
**Pull request by kojiromike**
closes #128 
closes #127 

also see #125
also see #126

### CODE REVIEW

**Comment by rycus86** [comment]
Legend, thanks a lot! I'll bump the version (and restore older Python version support perhaps) and tag it for release.

**Comment by kojiromike** [comment]
@rycus86 do you have a way I can add both versions of the client to the test matrix?

**Comment by rycus86** [comment]
Do you mean test with both versions of `prometheus_client`? I could imagine adding some pinning to the requirements.txt file before starting unit/integration tests, but I don't think it's necessary to be honest.

**Comment by kojiromike** [comment]
> Do you mean test with both versions of prometheus_client?

Right, it looks like you have a build matrix in Actions for testing different Python versions. I was just suggesting we could add a matrix for testing multiple versions of other dependencies, if you want.

**Comment by rycus86** [comment]
> we could add a matrix for testing multiple versions of other dependencies

Yes, we could but I don't think it's necessary (do you know other packages that do similar things?), but can reconsider later if this becomes a regular problem.

PS: love the branch name 👍

**Comment by csmarchbanks** [comment]
I just wanted to chime in here, sorry about the hassle! The rename was not meant as a breaking change, and I plan to revert back to the old name in https://github.com/prometheus/client_python/pull/796. It looks like with your fix will be fine. If you see breaking changes in prometheus_client in the future feel free to open an issue and I will try to resolve it as quickly as I can!

**Comment by Starkteetje** [comment]
Note that reverting the name change is a breaking change again for everyone pinning prometheus-flask-exporter 0.20

**Comment by rycus86** [comment]
Which is resolved in 0.20.1 :/

**Comment by Starkteetje** [comment]
Maybe I'm misunderstanding you, but 0.20.1 still doesn't seem to pin the prometheus-client version either in https://github.com/rycus86/prometheus_flask_exporter/blob/0.20.1/requirements.txt or https://github.com/rycus86/prometheus_flask_exporter/blob/0.20.1/setup.py

Compare i.e. with https://github.com/pallets/flask/blob/main/setup.py where the accepted versions are declared

Running `pip install prometheus-flask-exporter` this leads to `Requirement already satisfied: prometheus-client in ./lib/python3.8/site-packages (from prometheus-flask-exporter) (0.14.0)` but `Requirement already satisfied: Jinja2>=3.0 in ./lib/python3.8/site-packages (from flask->prometheus-flask-exporter) (3.1.1)`. So for prometheus-client any version is pulled, but for Jinja2 it needs to be >=3 due to the requirement in Flask's setup.py

Though to be fair `>=` wouldn't have prevented the incompatibility in this case as the breaking change was introduced without increasing the major version

**Comment by kojiromike** [comment]
@Starkteetje the fix in 0.20.1 does not require pinning. It is designed to work with either version-range of prometheus-client. If prometheus-client reverts the incompatibility, then 0.20.1 should still work.

**Comment by Starkteetje** [comment]
I see. That makes sense, especially in light of the change maybe being reverted.
However, the root cause is not tackled by this. A breaking change in Flask (less of an issue as its probably a direct dependency of whoever is using prometheus_flask_exporter) or a breaking change in prometheus-client are both likely to break existing setups. Pinning the version with `~=` would mitigate this if both dependencies adhere to semver (and prometheus-client had major version 1), so I'd still see value in that.
Pinning with `==` would resolve the issue completely, but that might be too strong of a dependency :man_shrugging:

**Comment by rycus86** [comment]
I don't think I want to start adding requirements on versions of dependencies here, I don't want this library to prescribe what versions it can work with. As long as we can reasonably make it work with different/multiple versions, we should be OK?

**Comment by rycus86** [comment]
> I just wanted to chime in here, sorry about the hassle! The rename was not meant as a breaking change, and I plan to revert back to the old name in [prometheus/client_python#796](https://github.com/prometheus/client_python/pull/796). It looks like with your fix will be fine. If you see breaking changes in prometheus_client in the future feel free to open an issue and I will try to resolve it as quickly as I can!

No worries, and thanks for looking into it! ❤️ I didn't even realize this library is on your radar. 😄

**Pull request merged**
